aws_region            = "us-east-#"
aws_vpc_id            = "vpc-#########"
aws_key_name          = "name"
aws_key_path          = "/home/ubuntu/.ssh/id_rsa"
aws_ami = "ami-################"
aws_instance_user = "ec2-user"
